"""Shared data and the excess-Gibbs-energy (G^E) head for the Part 1 re-runs with thermodynamically consistent
surrogates.

Molecules, labels and splits are those of aiomfac-surrogates v2.0.1, part1_organic_surrogate (notebook 01: pool,
hash split, label set of 20 water mass fractions x 4 temperatures; notebook 08: label set of 10 x 3 for Table 3),
regenerated by research/paper_5/code/s1_data.py (label set 1, identical sampling) and here (label set 2, synthetic
pretraining labels).

G^E head: for any molecular feature vector f, the network outputs h(f, w, T) (SiLU MLP) and
    g = G^E/(RT n) = x_w x_o h,  ln gamma_w = g - x_o dg/dx_o,  ln gamma_org = g + x_w dg/dx_o
(autograd; x_o is the organic mole fraction, w the water mass fraction w(x_o; M) with the AIOMFAC molar mass M of the
organic).  Gibbs-Duhem and the pure-component reference states hold by construction.
"""
from __future__ import annotations

import json
import os
import time

import numpy as np
import torch
import torch.nn as nn
from rdkit import Chem, RDLogger

RDLogger.DisableLog("rdApp.*")
torch.set_num_threads(int(os.environ.get("TORCH_THREADS", "2")))
P5 = str(__import__("pathlib").Path(__file__).resolve().parents[1] / "results")
MW = 0.01801528
D1 = np.load(f"{P5}/s1_labels.npz")
POOLJ = json.load(open(f"{P5}/s1_pool.json"))
POOL, VOCAB = POOLJ["pool"], POOLJ["vocab"]
PM, W, XO, TN, Y = D1["pm"], D1["w"], D1["x"], D1["tn"], D1["y"]
EXTRA = np.column_stack([W, TN]).astype(np.float32)
Y = Y.astype(np.float32)
CNT = D1["cnt"]
SRC = np.array([o["src"] for o in POOL])
CAT = np.array([o["cat"] for o in POOL])
H = np.array([o["hash100"] for o in POOL])
TEST = H < 15
MAIO = np.array([o["M_kg"] for o in POOL])          # AIOMFAC molar mass of the organic [kg/mol]


def _rdkit_feats(o):
    mol = Chem.MolFromSmiles(o["smiles"]); mh = Chem.AddHs(mol)
    sym = [a.GetSymbol() for a in mh.GetAtoms()]; nc = max(sym.count("C"), 1)
    return {"M": sum(a.GetMass() for a in mh.GetAtoms()), "oc": sym.count("O") / nc, "nc": sym.count("N") / nc}


for o in POOL:
    o.update(_rdkit_feats(o))


def pts_of(mask_mol, pm=None):
    pm = PM if pm is None else pm
    return np.where(mask_mol[pm])[0]


def x_of_w(w, M):
    a, b = (1 - w) / M, w / MW
    return a / (a + b)


fmt = lambda s: f"{np.mean(s):.3f} ± {np.std(s, ddof=1):.3f}" if len(s) > 1 else f"{np.mean(s):.3f}"


class GEHead(nn.Module):
    """h(f, w, T) -> G^E -> (ln gamma_w, ln gamma_org).  ``f`` already encoded (and standardized if applicable)."""

    def __init__(self, n_feat, hidden=128, L=3, drop=0.0):
        super().__init__()
        layers, d = [], n_feat + 2
        for _ in range(L):
            layers += [nn.Linear(d, hidden), nn.SiLU()] + ([nn.Dropout(drop)] if drop > 0 else [])
            d = hidden
        self.f = nn.Sequential(*layers, nn.Linear(d, 1))
        for name in ("wm", "ws", "tm", "ts", "hs"):
            self.register_buffer(name, torch.tensor(0.0 if name in ("wm", "tm") else 1.0))

    def set_norm(self, w, tn, y_org_std):
        self.wm.fill_(float(np.mean(w))); self.ws.fill_(float(np.std(w)) or 1.0)
        self.tm.fill_(float(np.mean(tn))); self.ts.fill_(float(np.std(tn)) or 1.0)
        self.hs.fill_(float(y_org_std))

    def forward(self, f, x, M, tn, create_graph=True):
        if not x.requires_grad:
            x = x.clone().requires_grad_(True)
        w = (1 - x) * MW / ((1 - x) * MW + x * M)
        z = torch.cat([f, ((w - self.wm) / self.ws)[:, None], ((tn - self.tm) / self.ts)[:, None]], 1)
        g = x * (1 - x) * self.f(z)[:, 0] * self.hs
        gp = torch.autograd.grad(g.sum(), x, create_graph=create_graph)[0]
        return torch.stack([g - x * gp, g + (1 - x) * gp], 1)


def split_pts(train_pts, seed, interp_split):
    tr = np.array(train_pts)
    if interp_split:
        p = np.random.RandomState(0).permutation(len(tr)); fit = tr[p[int(0.2 * len(tr)):]]
        nv = int(0.1 * len(fit)); return fit[:nv], fit[nv:]
    r0 = np.random.RandomState(seed); tr = tr.copy(); r0.shuffle(tr); nv = int(0.1 * len(tr))
    return tr[:nv], tr[nv:]


def fit_ge(rep, train_pts, seed, interp_split=False, max_epochs=500, patience=30, batch=256, label=None):
    """Train a G^E MLP with representation ``rep`` (R_emb, R_count, R_count', R_desc).  ``label`` = (PM, EXTRA, Y)
    of another label set (default: label set 1).  Returns predict(mol_idx_rows, extra_rows) -> (N, 2) and epochs."""
    pm, ex, yy = (PM, EXTRA, Y) if label is None else label
    val, fit = split_pts(train_pts, seed, interp_split)
    feats = FEATS[rep]
    Fm = feats[pm]
    if rep == "R_emb":
        fm, fs = np.zeros(Fm.shape[1]), np.ones(Fm.shape[1])
    else:
        fm, fs = Fm[fit].mean(0), Fm[fit].std(0); fs = np.where(fs < 1e-3, 1.0, fs)
        if rep == "R_count'":
            fm[:], fs[:] = 0.0, 1.0
    Fn = torch.tensor(((Fm - fm) / fs).astype(np.float32))
    xo = torch.tensor(x_of_w(ex[:, 0], MAIO[pm]).astype(np.float32)); Mt = torch.tensor(MAIO[pm].astype(np.float32))
    Tt = torch.tensor(ex[:, 1]); Yt = torch.tensor(yy)
    ym, ys = torch.tensor(yy[fit].mean(0)), torch.tensor(yy[fit].std(0) + 1e-6)
    torch.manual_seed(seed); rng = np.random.RandomState(seed)
    emb = nn.Linear(Fm.shape[1], 16, bias=False) if rep == "R_emb" else None
    head = GEHead(16 if rep == "R_emb" else Fm.shape[1]); head.set_norm(ex[fit, 0], ex[fit, 1], yy[fit, 1].std())
    params = list(head.parameters()) + (list(emb.parameters()) if emb is not None else [])
    opt = torch.optim.Adam(params, lr=1e-3, weight_decay=1e-5)

    def fwd(i, cg=True):
        f = emb(Fn[i]) if emb is not None else Fn[i]
        return head(f, xo[i], Mt[i], Tt[i], create_graph=cg)
    best, st, bad = 1e9, None, 0
    val_t = torch.tensor(val)
    for ep in range(max_epochs):
        head.train(); perm = rng.permutation(len(fit))
        for s in range(0, len(perm), batch):
            i = torch.from_numpy(fit[perm[s:s + batch]]); opt.zero_grad()
            (((fwd(i) - Yt[i]) / ys) ** 2).mean().backward(); opt.step()
        head.eval()
        v = (((fwd(val_t, cg=False).detach() - Yt[val_t]) / ys) ** 2).mean().item()
        if v < best - 1e-5:
            best, bad = v, 0
            st = ({k: t.clone() for k, t in head.state_dict().items()},
                  {k: t.clone() for k, t in emb.state_dict().items()} if emb is not None else None)
        else:
            bad += 1
            if bad >= patience:
                break
    head.load_state_dict(st[0])
    if emb is not None:
        emb.load_state_dict(st[1])
    head.eval()

    def predict(mol_rows, ex_rows):
        out = []
        for s in range(0, len(mol_rows), 50000):
            mr, er = mol_rows[s:s + 50000], ex_rows[s:s + 50000]
            f = torch.tensor(((feats[mr] - fm) / fs).astype(np.float32))
            if emb is not None:
                f = emb(f)
            x = torch.tensor(x_of_w(er[:, 0], MAIO[mr]).astype(np.float32))
            out.append(head(f, x, torch.tensor(MAIO[mr].astype(np.float32)), torch.tensor(er[:, 1].astype(np.float32)),
                            create_graph=False).detach().numpy())
        return np.concatenate(out)
    predict.modules = (emb, head, fm, fs)
    return predict, ep + 1


# molecular feature matrices (per molecule)
from aiomfac_py.params import load_subgroup_params  # noqa: E402
_sg = load_subgroup_params()
MGS = sorted({_sg.main_group(s) for s in VOCAB})


def desc(o, mgs=MGS):
    c, tq = np.zeros(len(mgs)), 0
    for s, q in o["subgroups"]:
        c[mgs.index(_sg.main_group(int(s)))] += q; tq += q
    return [*(c / max(tq, 1)), o["oc"], o["nc"], np.log(o["M"]), np.log1p(tq)]


DESC = np.array([desc(o) for o in POOL], np.float32)
FEATS = {"R_emb": CNT, "R_count": CNT, "R_count'": CNT, "R_desc": DESC}
REPS = ["R_count", "R_count'", "R_desc", "R_emb"]
T0 = time.time()
